aicore/contributor-license-agreement

employer_contributor_license_agreement.md, personal_contributor_licence_agreement.md
* Separate personal and employer-approved CLA.
* Accepting electronic signature instead of physical signature.
=> CLA split into personal and employer capacity.

README.md
* Updated readme file with steps on signing the CLA.
=> CLA signing instructions

docs/_config.yml, docs/index.md
=> CLA in github pages

docs/_layouts/default.html
=> addnig custom site layout

docs/img/button.svg, docs/index.md
Testing css button in markdown page
=> adding css buttons test

docs/img/employer_cla_button.svg, docs/img/personal_cla_button.svg, docs/img/revoke_cla_button.svg, docs/index.md
=> CLA ui buttons

docs/index.md
Fix url for revoke issue creation
=> fix url to revoke

docs/employer_cla.md, docs/img/employer_pull_cla_button.svg, docs/img/personal_pull_cla_button.svg, docs/index.md, docs/personal_cla.md
=> improved ux for cla signature

README.md, docs/img/sign_cla_button.svg
- Update cla sign instructions
- CLA sign instructions
=> Update cla sign instructions

personal_contributor_licence_agreement.md
Core.ai licence agreement signed
=> Signed agreement

personal_contributor_licence_agreement.md
Fixes: https://github.com/aicore/contributor-license-agreement/issues/17
=> Remove country names. fix layout

personal_contributor_licence_agreement.md
I have signed the personal_contributor_licence_agreement.md,
Regards,
Atheena Renjith
=> personal_contributor_licence_agreement.md signed

.github/PULL_REQUEST_TEMPLATE/sign_cla.md, .github/config.yml, .github/workflows/comment_pr.yml, .github/workflows/python/review_pr.py, .github/workflows/review_pr.yml, .gitignore
* Automatic pull request validations
* Integrate hello bot
=> Automated pr checkers

README.md, docs/employer_cla.md, docs/index.md, docs/personal_cla.md
* Validates that there is only a single commit
* a single file change
* other helpful messaging as part of cla
=> Auto review of pull requests with cla signatures

.github/workflows/comment_pr.yml, .github/workflows/python/diff_parser.py, .github/workflows/python/review_pr.py, .github/workflows/review_pr.yml, .gitignore
* Added validations for CLA sign workflow
=> PR validations

.github/workflows/python/review_pr.py, .gitignore
Solve task 1 in https://github.com/aicore/contributor-license-agreement/issues/27#issue-924913290.
Verify that the row added in the table is valid syntax.
=> Add validate line format

.github/workflows/python/review_pr.py
Solve task 2 in https://github.com/aicore/contributor-license-agreement/issues/27#issue-924913290.
Verify that the GitHub id provided in the table is the GitHub ID raising the pull request.
=> Add git username validation

.github/workflows/python/review_pr.py
Solve task 3 in https://github.com/aicore/contributor-license-agreement/issues/27#issue-924913290.
Verify that the date mentioned in the table is valid and within one week of the pull request submission date.
=> Add validate date

.github/workflows/python/review_pr.py
Solve task 4 in https://github.com/aicore/contributor-license-agreement/issues/27#issue-924913290.
Validate user has not signed the CLA before in either personal or employer capacity.
=> Add validate if already signed

.github/workflows/python/review_pr.py
=> Format comment

employer_contributor_license_agreement.md
Removing from employer cla as as i have already signed in personal cla
=> Already signed in personal capacity
